AbhiGattineni/Anddhen-Group

src/components/inc/Mywork.js
src/components/pages/Home.js

New component Our Work is added to webpage

Added new component Our Works

---

src/components/pages/inc/Vmc.js

paragraph updation

---

src/components/SuperAdmin/OurTeam/editTeamMember.jsx
src/components/SuperAdmin/OurTeam/viewTeamMember.jsx
src/components/organisms/Modal/AssTeamModel.jsx

https://www.notion.so/no-scrollbar-for-edit-model-in-ourTeam-page-15956cf0f98a809a886ec5bad73bb316

bugs in outteam page

---

src/components/generalComponents/TransactionTable.jsx
src/components/organisms/Modal/TransactionModal.jsx
src/components/organisms/Utils.jsx
src/components/pages/inc/Aps.jsx

https://github.com/user-attachments/assets/91c3ead8-82fb-4f53-af3c-de10b01f66c4
https://www.notion.so/Transactions-to-show-up-in-APS-page-15356cf0f98a80009ae5edb0b83512da?v=dc7c54eab9fe4fb29d5686009975ce3b

transaction component added in the APS page

---

package-lock.json
package.json
public/index.html
src/components/pages/inc/Acs.jsx
src/index.js

changes the title of the asc page with content
and added some features of seo like added the link tags

added the seo features

---

src/components/SuperAdmin/ACS/Consultants/Employer.jsx
src/components/SuperAdmin/ACS/Consultants/Recruiter.jsx
src/components/pages/Admin/EmployeeDashboard.jsx

pagination for Employer Management
pagination for Recruiter Management
removec search bar when cards are not available in employeedashboard
https://github.com/user-attachments/assets/0721bd47-407b-4310-a1a2-b8e33616cf1e
https://anddhengroup.atlassian.net/browse/AGS-5?atlOrigin=eyJpIjoiYWMxOTMxZWEwMzllNDQ2ZWI2ZTA2MWVlNzYwMTQ1M2UiLCJwIjoiaiJ9

pagination for Employer Management & Recruiter Management , search bar edit

---

src/components/SuperAdmin/transactions/Transaction.jsx

Make credit and debit in 1 single column as amount and colors should vary as per type.
like debit should be RED
credit should be GREEN
tested if Sender and receiver name first letter should be capital letters
https://github.com/user-attachments/assets/545742c4-0093-4c6a-850f-e9a37d3e4387
https://anddhengroup.atlassian.net/browse/AGS-6

removed credit and debit amount and made single row of amount

---

src/components/SuperAdmin/Status.jsx

https://github.com/user-attachments/assets/98171b25-9b34-41e4-a512-8ec87afcb0c0
https://anddhengroup.atlassian.net/browse/AGS-48

status view added

---

src/components/SuperAdmin/ACS/Colleges/CollapsibleTable.jsx

https://github.com/user-attachments/assets/f05de7ba-b514-4725-8045-cd13210e39e7
https://anddhengroup.atlassian.net/browse/AGS-41

state filter added in college

---

package-lock.json
src/components/SuperAdmin/ACS/Consultants/Employer.jsx
src/components/SuperAdmin/ACS/Consultants/Recruiter.jsx

delete was not working at the first instance in employee and recruiter the bug is resolved 
https://anddhengroup.atlassian.net/browse/AGS-30
https://github.com/user-attachments/assets/eaf1d775-0a36-4594-8260-060f211117f9
https://github.com/user-attachments/assets/5e315d66-fe95-478a-8d35-fa1e7e879471

delete for employee and recruiter in consultant page

---

src/components/generalComponents/TransactionTable.jsx

there was no message when there was no fields to display which is resolved
https://anddhengroup.atlassian.net/browse/AGS-56
https://github.com/user-attachments/assets/63cd1c8f-dc9b-4457-89c5-61287bfa9813

fixed the isuue in transaction table in aps

---

src/components/pages/Auth/ForgotPassword.jsx

https://anddhengroup.atlassian.net/browse/AGS-40
https://github.com/user-attachments/assets/9260e418-9369-44f9-925e-b7e70298f50e

forgot password updated

---

src/components/SuperAdmin/ACS/Colleges/CollapsibleTable.jsx
src/components/SuperAdmin/OurTeam/viewTeamMember.jsx
src/components/organisms/CollegeWhatsappLinks.js

error code handling and no fields to show 
https://anddhengroup.atlassian.net/browse/AGS-81
education consulting
ass team members
collage whatsapp links

error code handling

---

src/components/organisms/ImageSlider/ImageSlider.jsx
src/components/pages/inc/Ass.jsx

change in style of slider in ass
https://anddhengroup.atlassian.net/browse/AGS-50
https://github.com/user-attachments/assets/510ed4a8-41fa-4e1d-9ab1-01d15449f2b7

change in style of slider in ass

---

src/components/generalComponents/TransactionTable.jsx

https://anddhengroup.atlassian.net/browse/AGS-63
merged the amount column into one column

merge the columns in APS transaction

---

src/components/SuperAdmin/transactions/Transaction.jsx
src/components/atoms/Search/ReactSelectDropdown.jsx
src/components/pages/Admin/EmployeeDashboard.jsx

https://anddhengroup.atlassian.net/browse/AGS-95

filters added to the transaction table

---

src/components/organisms/Modal/AssProjectModal.jsx
src/components/organisms/Modal/AssTeamModel.jsx
src/components/organisms/Modal/TransactionModal.jsx

https://anddhengroup.atlassian.net/browse/AGS-78

close button fixed

---

src/components/pages/resume/ResumeComponent.jsx
src/components/pages/resume/ResumeHome.jsx

https://anddhengroup.atlassian.net/browse/AGS-64

added the parser feature

---

src/App.css
src/components/pages/Admin/EmployeeDashboard.jsx
src/react-query/useStatusUpdateMutation.jsx

spacing was removed for APS and ATS pages
https://anddhengroup.atlassian.net/browse/AGS-108

side space fixed

---

src/components/SuperAdmin/Status.jsx

https://anddhengroup.atlassian.net/browse/AGS-163

status error resolved

---

src/components/pages/Admin/EmployeeDashboard.jsx

https://anddhengroup.atlassian.net/browse/AGS-162
happiness index is not appearing after submitted.

happiness index bug resolved

---

src/dataconfig.js

Removed simplify video from job applications page.
https://anddhengroup.atlassian.net/browse/AGS-160

removed simplify video

---

src/components/organisms/ImageSlider/ImageSlider.jsx

change in the design of the cards
https://anddhengroup.atlassian.net/browse/AGS-156

changed Cards design

---

src/components/pages/Admin/EmployeeDashboard.jsx

https://anddhengroup.atlassian.net/browse/AGS-172

fixed the leave field in employeedashboard

---

package-lock.json
src/components/organisms/ImageSlider/ImageSlider.jsx
src/components/pages/Admin/EmployeeDashboard.jsx

All status should get closed by next day 9:00 AM local timezone of  user
https://anddhengroup.atlassian.net/browse/AGS-66
https://github.com/user-attachments/assets/d7e76b6a-d46d-4326-9f50-c4ef2a7e19ed

updating status within next day

---

src/components/pages/ACS/PartTimerPortal.jsx
src/components/pages/ACS/StudentPortal.jsx
src/components/pages/Extension/ExtensionDetails.jsx
src/components/pages/inc/Acs.jsx
src/components/pages/inc/Ams.jsx
src/components/pages/inc/Ass.jsx
src/index.js

https://anddhengroup.atlassian.net/browse/AGS-217
https://anddhengroup.atlassian.net/browse/AGS-254

fixed the husky file

---

src/components/SuperAdmin/Status.jsx
src/components/pages/Admin/EmployeeDashboard.jsx

https://anddhengroup.atlassian.net/browse/AGS-261
https://github.com/user-attachments/assets/3fbf146f-598f-400b-ac84-5d92095b240f

subsidiary view added in status card

---

src/components/pages/inc/VideoEditor.jsx

https://github.com/user-attachments/assets/6dcd7a95-5d6f-4082-af9f-ab11976d64e0
https://anddhengroup.atlassian.net/browse/AGS-59

video tool updated

---

src/components/SuperAdmin/ACS/Colleges/AddColleges.jsx
src/components/organisms/InputField.jsx

https://anddhengroup.atlassian.net/browse/AGS-364

removed the required fields

---

src/components/organisms/Modal/TransactionModal.jsx

https://anddhengroup.atlassian.net/browse/AGS-342
Added a full-screen dark overlay div that appears behind the modal
The overlay has:
position-fixed to cover the entire viewport
Full width and height (w-100 h-100)
Semi-transparent black background (rgba(0, 0, 0, 0.5))
z-index just below the modal
Shows/hides with the modal

added grey background

---

src/components/SuperAdmin/Status.jsx
src/components/pages/Admin/EmployeeDashboard.jsx
src/components/templates/StatusCalender.jsx

https://github.com/user-attachments/assets/3a3ef6f1-b89c-431a-9fa5-7bc57382100a
https://anddhengroup.atlassian.net/browse/AGS-361
StatusCalendar.jsx
Made component controlled - no more internal state, parent controls everything
Removed side effects - doesn't update global store anymore
Added PropTypes - proper validation for all props
Status.jsx
Added monthly stats - shows working days, leaves, empty days count
Added loading states - spinners for employees, calendar, and status data
Enhanced layout - calendar left, stats right, responsive design
Fixed PropTypes warning - added validation for LoadingSpinner text prop
EmployeeDashboard.jsx
Updated for new calendar - now controls StatusCalendar with props
Added date state management - handles calendar date changes
Removed unused variables - …

month stats are added in status

---

src/components/pages/Admin/EmployeeDashboard.jsx

https://anddhengroup.atlassian.net/browse/AGS-363
https://github.com/user-attachments/assets/e146ca87-b327-4d4b-ae2f-950e933df686

added multiple leaves feature

---

src/components/generalComponents/StatusTable.jsx

Uploading Screen Recording 2025-08-22 174606.mp4…
https://anddhengroup.atlassian.net/browse/AGS-359
Added a horizontal and vertical scrollbar to the table with custom styling.
Changed table header sticky for better UX.
Showing the latest records at the top.

scroll bar added

---

src/components/SectionAccordion.jsx
src/components/pages/OnboardingTask.jsx
src/dataconfig.js
src/routes/getSharedRoutes.js

https://github.com/user-attachments/assets/caa5f8db-d676-4537-a2cb-5a09c7794b54
https://anddhengroup.atlassian.net/browse/AGS-369

onboarding feature
